name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: aihomeassist
  APP_NAME: ai-homeasst

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Logs into Azure (service principal format)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Logs into the container registry
    - name: Azure Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Build & push Docker image with the commit SHA
    - name: Build and Push Image
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
    
    # Deploy to Azure Container Instances
    - name: Deploy to ACI
      uses: azure/aci-deploy@v1
      with:
        resource-group: DockerRG
        dns-name-label: ${{ env.APP_NAME }}
        image: ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
        registry-login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ env.APP_NAME }}
        location: southindia
        cpu: 1
        memory: 1.5
        ports: 3000 1883
        environment-variables: |
          MQTT_BROKER_URL=mqtt://localhost
          MQTT_PORT=1883
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
