name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: aihomeassist     # Your ACR name (no ".azurecr.io" here)
  APP_NAME: ai-home-asst         # Internal name for your container instance

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Check out your code
    - uses: actions/checkout@v3
    
    # 2. Login to Azure using the service principal JSON in AZURE_CREDENTIALS
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # 3. Login to ACR
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # 4. Build & push the Docker image using the Git commit SHA as the tag
    - name: Build and Push Image
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
    
    # 5. Deploy the container image to Azure Container Instances
    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: DockerRG
        dns-name-label: ${{ env.APP_NAME }}       # Creates a subdomain like ai-home-asst.southindia.azurecontainer.io
        image: ${{ env.REGISTRY_NAME }}.azurecr.io/ai-home-asst:${{ github.sha }}
        registry-login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ env.APP_NAME }}
        location: southindia
        cpu: 1
        memory: 1.5
        ports: 3000 1883
        environment-variables: |
          MQTT_BROKER_URL=mqtt://localhost
          MQTT_PORT=1883
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}