name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_NAME: aihomeassist
  APP_NAME: ai-home-asst

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aihomeassist.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Push Image
      run: |
        docker build . -t aihomeassist.azurecr.io/ai-home-asst:${{ github.sha }}
        docker push aihomeassist.azurecr.io/ai-home-asst:${{ github.sha }}
    
    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: DockerRG
        dns-name-label: aihomeassist
        image: aihomeassist.azurecr.io/ai-home-asst:${{ github.sha }}
        registry-login-server: aihomeassist.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aihomeassist
        location: 'southindia'
        cpu: 1
        memory: 1.5
        ports: 3000 1883
        environment-variables: |
          MQTT_BROKER_URL=mqtt://localhost
          MQTT_PORT=1883
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
 